ask_role = 'Specify a role eligible to post anonymously.'
ask_channel = 'Specify a channel to post anonymously in'
ask_header = 'Specify a header'
init_complete = 'initialization complete!'
overwrite_init = 'This bot is already initialized, are you sure? (y/n)'
overwrite_aborted = 'Aborted'

# Error
uninitialized = 'Bot is not initialized!'
not_owner = "Sorry, this command can only be executed by the server owner."
ineligible = "Sorry, you don't belong to the eligible class \"{role}\""
invalid_role = 'This role is invalid or cannot be found'
invalid_channel = 'This channel cannot be found'
counter_parse_error = 'Cannot parse value'
